### PR TITLE
add: options.variables

### PR DESCRIPTION
**Pull request by davemo**
- allows users to control output of base64 encoded images as SASS/SCSS variables.

We've been using grunt-datauri at Shopify for placeholder selectors but many of our designers also want some more flexibility with the encoded images. This PR adds support for emitting SASS/SCSS variables which can then be used in cases like supporting multiple background images.

I've added tests and updated the README as well :)

### CODE REVIEW

**Comment by ceee** [comment]
Hi!
Thanks a lot for your PR, it's a great addition.
I'm currently at work, but will test & merge it when I'm home today.

**Comment by davemo** [comment]
Sounds good @ceee :)

**Comment by davemo** [comment]
Thanks, can you push a release to NPM? :)

**Comment by ceee** [comment]
It's pushed now!
Thanks for your work - you are listed as a contributor now ;-)

**Comment by davemo** [comment]
:sparkles: :+1: :)

**Pull request merged**
